export const projects = [
  {
    title: 'Small-Talks',
    description: "Small-Talks is an online platform where anyone can post messages, updates and news regarding skills, resources, job post and can new technologies in Public. (Purpose):- To build a social networking service website for students to share words privately and talk openly in small talks.",
      image: '/images/1.png',
      tags: ['NextJS', 'Firebase', 'Reactjs','Nodesjs'],
    source: 'https://github.com/Mat-Fraser/Small-Talks',
    visit: 'https://small-talks.vercel.app/',
    id: 0,
  },
  {
    title: 'NFt-Store',
    description:"NFt-Store is a simple e-commerce website where we can buy NFTs.Next is used for the front end and payment option through Stripe API(test mode).(Purpose):- To learn and explore about the e-commerce website projects,and showcase my and my friend's NFTs.",
    image: '/images/nft.png',
    tags: ['React', 'NextJS','Stripe(API)','Vercel'],
    source: 'https://github.com/Mat-Fraser/online-nft-store ',
    visit: 'https://online-nft-store.vercel.app/',
    id: 1,
  },
  {
    title: 'Algos',
    description: "Algos is an algorithms visualizer that helps you visualize Shortest path algorithms and Sorting algorithms.Such as::- Dijkstra’s Shortest Path Algorithm, A* Search Algorithm, Bubble Sort, Selection Sort, Insertion Sort, Quick Sort, and Merge Sort.",
      image: '/images/algos.png',
      tags: ['DSA','React','JavaScript','Netlify'],
    source: 'https://github.com/Mat-Fraser/Algos',
    visit: 'https://algos-cover.netlify.app/',
    id: 2,
  },
  {
    title: 'Crypto Tracker',
    description: "It is a cryptocurrency price tracking app that stalks the prices of cryptocurrencies such as bitcoin, Ethereum, Dogecoin, etc. Using next for the frontend and powered by CoinGecko API.",
    image: '/images/cyt.png',
    tags: ['React', 'NextJS', 'CoinGecko(API)','Vercel'],
    source: 'https://github.com/Mat-Fraser/crypto-tracker',
    visit: 'https://crypto-tracker-eosin.vercel.app/',
    id: 3,
  },
    {
    title: 'Solver Sudoku ',
    description: "Sudoku is a logic-based, combinatorial number placement puzzle. And it comes with some extra features such as username, different difficulty modes, clean UI, and continue functionality.",
    image: '/images/sudoku.png',
    tags: ['HTML', 'CSS', 'JavaScript','Netlify'],
    source: 'https://github.com/Mat-Fraser/Sudoku-Solver',
    visit: 'https://solversudoku.netlify.app/',
    id: 4,
  },
    {
    title: 'Videos-Transcripter',
    description: "It is a video transcript application that takes a youtube video URL and converts them to text format. that converts the audio file to text format.",
    image: '/images/trans.png',
    tags: ['Python', 'Assembly(API)', 'Streamlit'],
    source: 'https://github.com/Mat-Fraser/Video-Transcription-app',
    visit: 'https://github.com/Mat-Fraser/Video-Transcription-app',
    id: 5,
  },
];
export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];

export const miniprojects = [  
  {
  title: 'Portfolio_1.0',
  description: "My old portfolio wesite WITH PERFECT SCORE.",
    image: '/images/mini.png',
    tags: ['HTML', 'CSS','JS','Netlify'],
  source: 'https://google.com',
  visit: 'https://google.com',
  id: 0,
},
{
  title: 'Analog Clock',
  description:"( Analog + Digital ) Clock with clean UI and comes with Light and Dark modes.",
  image: '/images/mini.png',
  tags: ['HTML', 'Css', 'Scss','JS'],
  source: 'https://github.com/Mat-Fraser/Analog_clock',
  visit: 'https://analog-clock-aks.netlify.app/',
  id: 1,
},
{
  title: 'Developers reads (online book store)',
  description: "Front-end design with clean UI, great digital experience with LOGIN FORM ",
    image: '/images/mini.png',
    tags: ['HTML', 'CSS', 'JS','Netlify'],
  source: 'https://github.com/Mat-Fraser/Developers-Reads-Online-Book-store-',
  visit: 'https://dev-reads.netlify.app/',
  id: 2,
}];

export const miniprojects2 = [  
  {
  title: 'Audio-transcripter(Nodejs)',
  description: "It is an nodejs project that helps you transcribe audio files to text.",
    image: '/images/mini.png',
    tags: ['JS', 'API', 'NodeJS'],
  visit: ' https://github.com/Mat-Fraser/audio-transcripter',
  id: 0,
},
{
  title: 'Spotify-Clone_Web3.0',
  description:"A digital music service that gives you access to millions of songs.",
  image: '/images/mini.png',
  tags: ['HTML','Css','Solidity', 'JS'],
  visit: 'https://github.com/Mat-Fraser/Spotify-Clone_Web3.0 ',
  id: 1,
},
{
  title: 'Wordle_clone ',
  description: "It is a clone wordle, web-based word game that was bought by NY Times in million dollars.",
    image: '/images/mini.png',
    tags: ['HTML', 'CSS', 'JS'],
  visit: 'https://github.com/Mat-Fraser/Wordle_clone',
  id: 2,
}];
